/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionIdRouteImport } from './routes/subscription.$id'
import { Route as SubscriptionIdEditRouteImport } from './routes/subscription.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIdRoute = SubscriptionIdRouteImport.update({
  id: '/subscription/$id',
  path: '/subscription/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIdEditRoute = SubscriptionIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SubscriptionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/subscription/$id': typeof SubscriptionIdRouteWithChildren
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/subscription/$id': typeof SubscriptionIdRouteWithChildren
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/subscription/$id': typeof SubscriptionIdRouteWithChildren
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/subscription/$id'
    | '/subscription/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/subscription/$id'
    | '/subscription/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/subscription/$id'
    | '/subscription/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  SubscriptionIdRoute: typeof SubscriptionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/$id': {
      id: '/subscription/$id'
      path: '/subscription/$id'
      fullPath: '/subscription/$id'
      preLoaderRoute: typeof SubscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/$id/edit': {
      id: '/subscription/$id/edit'
      path: '/edit'
      fullPath: '/subscription/$id/edit'
      preLoaderRoute: typeof SubscriptionIdEditRouteImport
      parentRoute: typeof SubscriptionIdRoute
    }
  }
}

interface SubscriptionIdRouteChildren {
  SubscriptionIdEditRoute: typeof SubscriptionIdEditRoute
}

const SubscriptionIdRouteChildren: SubscriptionIdRouteChildren = {
  SubscriptionIdEditRoute: SubscriptionIdEditRoute,
}

const SubscriptionIdRouteWithChildren = SubscriptionIdRoute._addFileChildren(
  SubscriptionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  SubscriptionIdRoute: SubscriptionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
